#!/usr/bin/python

# This tool generates a json file for test-suite-score.
# There are some rules for the selected-revs data.
# The tool reads the first number as revision number from the name of the .txt file and the code element names from the file.
# Fails file contains revision number and total failed testcase

import argparse
import os
import json

# main function
def main():
    parser = argparse.ArgumentParser(description='test-suite-score-json-gen generates json file for test-suite-score')
    parser.add_argument('-c', '--coverage-data', required=True, help='Path to the coverage matrix file')
    parser.add_argument('-r', '--results-data', required=True, help='Path to the results matrix file')
    parser.add_argument('-a', '--cluster-algorithm', default="one-cluster", help='Name of the cluster algorithm')
    parser.add_argument('-o', '--output', required=True, help='Output file path and name.')
    parser.add_argument('--fail', required=True, help='Path to the fail.csv file generated by test-selection-statistics')
    parser.add_argument('-s', '--source-directory', required=True, help='Path to the directory where the text files contains the failed code element names and the name of the file contains the revision number')
    parser.add_argument('-g', '--globalize', type=bool, default=False, help='Globalize selection data')
    parser.add_argument('--output-dir', required=True, help='Output directory for test-suite-score')
    parser.add_argument('-f', '--fault-localization-techniques', nargs='*', default=["ochiai", "tarantula"], help='Fault localization techniques for test-suite-score')

    generateJson(parser.parse_args())

# reads revision; fail data from fails statistics
def readFails(path):
    fail = dict()
    with open(path) as f:
        nOfRevs = f.readline()
        nOfRevs = int(nOfRevs.split(';')[1])
        for x in range(0, nOfRevs + 2):
            line = f.readline()
            if x < 2:
                continue
            line = line.split(';')
            fail[line[0]] = int(line[1]) #revision ; fails

    return fail


# reads failed code element names from file
def readCodeElementNames(path):
    failedCodeElements = list()
    with open(path) as f:
        for line in f:
            failedCodeElements.append(line.strip())

    return failedCodeElements

# generates part of json file for test-suite-score
def generateJson(args):
    revCount = 0
    of = open(args.output + '.json', 'w')
    fail = readFails(args.fail)
    conf = dict()
    conf["coverage-data"] = args.coverage_data
    conf["results-data"] = args.results_data
    conf["cluster-algorithm"] = args.cluster_algorithm
    conf["fault-localization-techniques"] = args.fault_localization_techniques
    conf["globalize"] = args.globalize
    conf["output-dir"] = args.output_dir
    conf["selected-revisions"] = list()
    
    selectedrevs = list()
    
    for dirpath, dirnames, filenames in os.walk(args.source_directory):
        for file in filenames:
            # name splitting
            name, ext = os.path.splitext(file)
            if ext != '.txt':
                continue

            revision = ''
            digit = False
            # revision number
            for c in name:
                if not digit and c.isdigit():
                    digit = True

                if digit and not c.isdigit():
                    break

                if digit:
                    revision += c

            # code element names from file
            failedCodeElements = readCodeElementNames(os.path.join(dirpath, file))

            if revision == '':
                continue

            # json format
            conf["selected-revisions"].append({ "revision": revision ,"failed-code-elements": failedCodeElements,"total-failed-testcases": fail[revision] })
            revCount += 1

    of.write(json.dumps(conf, separators=(',',': '), indent=4, sort_keys=False))
    of.close()
    print(str(revCount) + ' selected revisions generated...')

if __name__ == '__main__':
    main()
